parameters: 
    prooph_service_bus.command_bus_router.class: Prooph\ServiceBus\Plugin\Router\CommandRouter
    prooph_service_bus.command_bus.class: Prooph\ServiceBus\CommandBus
services:
    prooph_service_bus.command_bus:
        class: '%prooph_service_bus.command_bus.class%'
        factory: ['@prooph_service_bus.command_bus_factory', create]
    prooph_service_bus.command_bus_factory:
        class: '%prooph_service_bus.message_bus_factory.class%'
    prooph_service_bus.command_bus_router:
        class: '%prooph_service_bus.command_bus_router.class%'
