parameters: 
  prooph_event_store.metadata_enricher_plugin.class: Prooph\EventStore\Metadata\MetadataEnricherPlugin
  prooph_event_store.metadata_enricher_aggregate.class: Prooph\EventStore\Metadata\MetadataEnricherAggregate
  prooph_event_store.message_converter.class: Prooph\Common\Messaging\NoOpMessageConverter
  prooph_event_store.message_factory.class: Prooph\Common\Messaging\FQCNMessageFactory
  prooph_event_store.action_event_emitter.class: Prooph\Common\Event\ProophActionEventEmitter
  prooph_event_store.repository.class: Prooph\EventSourcing\Aggregate\AggregateRepository
  prooph_event_store.repository_factory.class: Pac\ProophPackage\Factory\RepositoryFactory
  prooph_event_store.store_factory.class: Pac\ProophPackage\Factory\EventStoreFactory
  prooph_event_store.stream_table_map: []
    
services: 
  prooph_event_store.store_definition:
    class:  Prooph\EventStore\EventStore
  prooph_event_store.store_factory:
    class: '%prooph_event_store.store_factory.class%'
  prooph_event_store.plugin_definition:
    class:  Prooph\EventStore\Plugin\Plugin
  prooph_event_store.metadata_enricher_plugin_definition:
    class: '%prooph_event_store.metadata_enricher_plugin.class%'
  prooph_event_store.metadata_enricher_aggregate_definition:
    class: '%prooph_event_store.metadata_enricher_aggregate.class%'
  prooph_event_store.repository_factory:
    class: '%prooph_event_store.repository_factory.class%'
  prooph_event_store.repository_definition:
    class: '%prooph_event_store.repository.class%'
  prooph_event_store.action_event_emitter:
    class: '%prooph_event_store.action_event_emitter.class%'
  prooph_event_store.message_converter:
    class: '%prooph_event_store.message_converter.class%'
  prooph_event_store.message_factory:
    class: '%prooph_event_store.message_factory.class%'
