parameters:
  prooph_service_bus.message_bus_factory.class: Pac\ProophPackage\Factory\MessageBusFactory
  prooph_service_bus.message_factory_plugin.class: Prooph\ServiceBus\Plugin\MessageFactoryPlugin
  prooph_service_bus.message_factory.class: Prooph\Common\Messaging\FQCNMessageFactory
  prooph_service_bus.container_plugin.class: Prooph\ServiceBus\Plugin\ServiceLocatorPlugin

services:
  prooph_service_bus.handle_command_invoke_strategy:
    class: 'Prooph\ServiceBus\Plugin\InvokeStrategy\HandleCommandStrategy'
  prooph_service_bus.finder_invoke_strategy:
    class: 'Prooph\ServiceBus\Plugin\InvokeStrategy\FinderInvokeStrategy'
  prooph_service_bus.on_event_invoke_strategy:
    class: 'Prooph\ServiceBus\Plugin\InvokeStrategy\OnEventStrategy'
  prooph_service_bus.message_factory_plugin:
    class: '%prooph_service_bus.message_factory_plugin.class%'
  prooph_service_bus.message_factory:
    class: '%prooph_service_bus.message_factory.class%'
  prooph_service_bus.container_plugin:
    class: '%prooph_service_bus.container_plugin.class%'
    arguments:
      - '@service_container'
